version: '3'

services:
  db:
    container_name: astra_network_db
    hostname: astra_network_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  elastic:
    container_name: astra_network_elastic
    hostname: astra_network_elastic
    image: elasticsearch:6.6.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
#      ports:
#        - 9200:9200
  app:
    container_name: astra_network_app
    hostname: astra_network_app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/var/www/astra_network/src
    ports:
      - "5000:5000"
    depends_on:
      - db
      - elastic

volumes:
  nest_example_data:

